#!/usr/bin/env Rscript
library(Seurat)
library(SeuratDisk)
library(ggplot2)
library(cowplot)
library(dplyr)
library(pheatmap)

# Setting directories and flags
x.celltype = ""
Project_name = paste0("x_All_", x.celltype)
Input.dir = "Output/4_Subsetting/"
FindMarker.flag = TRUE
ScaleData.flag = FALSE
SingleR.flag = FALSE
annotation.done = TRUE
theme_set(theme_cowplot())
Norm.assay = "RNA"

# Setting markers
Cellmarkers = c("AR", "ESR1", "PGR")

if (dir.exists(path = paste0("Output/5_", x.celltype, "_Clustering")) == FALSE) {
  print(paste0("Generating output directory"))
  dir.create(path = paste0("Output/5_", x.celltype, "_Clustering"), recursive = TRUE)
  Output.dir = paste0("Output/5_", x.celltype, "_Clustering/")
} else if (dir.exists(path = paste0("Output/5_", x.celltype, "_Clustering")) == TRUE) {
  print("Directory exists")
  Output.dir = paste0("Output/5_", x.celltype, "_Clustering/")
} else {
  print("Error with output directory")
}

# Loading reclustered Seurat
print("Seurat object loading")
x.integrated = LoadH5Seurat(file = paste0(Input.dir, Project_name, "_reclustered.h5seurat"))

# Loading immune markers from FindAllMarkers
cluster.markers = readRDS(paste0("Output/4_Subsetting/", Project_name, "_FindAllMarkers.rds"))
cluster.markers.top10 = readRDS("Output/4_Subsetting/", Project_name, "_FindAllMarkers_top10.rds")

UMAP_original_label = DimPlot(x.integrated, reduction = "umap", group.by = "Labelled_Clusters",)
ggsave2(plot =  UMAP_original_label, filename = paste0(Output.dir,Project_name,"_Labelled_Clusters.pdf"), dpi = 700)
print("Done with basic UMAP")  

# Plotting function
Marker_plotting <- function(marker, name, group, selected.assay = Norm.assay) {
  
  print(paste("Plotting", name, "with", selected.assay))
  
  DefaultAssay(x.integrated) = selected.assay
  VlnPlot(x.integrated, features = marker, pt.size = 0, sort = "increasing", group.by = group)
  ggsave2(paste0(Output.dir, Project_name, "_", group, "_", name, "_", Norm.assay, "_Marker_ViolinPlot.pdf"), dpi = 700)
  
  FeaturePlot(x.integrated, features = marker)
  ggsave2(paste0(Output.dir, Project_name, "_", group, "_", name, "_", Norm.assay, "_Marker_FeaturePlot.pdf"), dpi = 700)
  
  DotPlot(object = x.integrated, features = marker, group.by = group) + RotatedAxis()
  ggsave2(paste0(Output.dir, Project_name, "_", group, "_", name, "_", Norm.assay, "_Marker_Dotplot.pdf"), dpi = 700)
}

# Plotting QC metric between groups, samples and clusters
Plotting_QC <- function(x, group = "") {
  
  # Generating ridgeplots
  RidgePlot(x.integrated, features = "percent.mt", group.by = group)
  ggsave2(paste0(Output.dir,Project_name, "_",group, "_Ridgeplot_mtDNA.pdf"), dpi = 700)
  
  RidgePlot(x.integrated, features = "nCount_RNA", group.by = group)
  ggsave2(paste0(Output.dir,Project_name, "_",group, "_Ridgeplot_nCount_RNA.pdf"), dpi = 700)
  
  RidgePlot(x.integrated, features = "nFeature_RNA", group.by = group)
  ggsave2(paste0(Output.dir,Project_name, "_",group, "_Ridgeplot_nFeature_RNA.pdf"), dpi = 700)
  
  RidgePlot(x.integrated, features = "S.Score", group.by = group)
  ggsave2(paste0(Output.dir,Project_name, "_",group, "_Ridgeplot_S-Score.pdf"), dpi = 700)
  
  RidgePlot(x.integrated, features = "G2M.Score", group.by = group)
  ggsave2(paste0(Output.dir,Project_name, "_",group, "_Ridgeplot_G2M-Score.pdf"), dpi = 700)
  
  # Generating violin plots
  VlnPlot(x.integrated, features = "percent.mt", group.by = group, pt.size = 0)
  ggsave2(paste0(Output.dir,Project_name, "_",group, "_Vlnplot_mtDNA.pdf"), dpi = 700)
  
  VlnPlot(x.integrated, features = "nCount_RNA", group.by = group, pt.size = 0)
  ggsave2(paste0(Output.dir,Project_name, "_",group, "_Vlnplot_nCount_RNA.pdf"), dpi = 700)
  
  VlnPlot(x.integrated, features = "nFeature_RNA", group.by = group, pt.size = 0)
  ggsave2(paste0(Output.dir,Project_name, "_",group, "_Vlnplot_nFeature_RNA.pdf"), dpi = 700)
  
  VlnPlot(x.integrated, features = "S.Score", group.by = group, pt.size = 0)
  ggsave2(paste0(Output.dir,Project_name, "_",group, "_Vlnplot_S-Score.pdf"), dpi = 700)
  
  VlnPlot(x.integrated, features = "G2M.Score", group.by = group, pt.size = 0)
  ggsave2(paste0(Output.dir,Project_name, "_",group, "_Vlnplot_G2M-Score.pdf"), dpi = 700)
  
}

# Running markerplotting on seurat clusters with RNA assay
Idents(object = x.integrated) <- "seurat_clusters"
DefaultAssay(x.integrated) = Norm.assay

run = Marker_plotting(marker = Cellmarkers, name = "Cellmarkers", group = "seurat_clusters")

if (SingleR.flag == TRUE) {
  
  library(SingleR)
  library(celldex)
  
  # Setting annotation for SingleR annotation
  SingleR.annotation.ref.Monaco = celldex::MonacoImmuneData()
  SingleR.annotation.ref.DbImmune = celldex::DatabaseImmuneCellExpressionData(cell.ont = "nonna")
  SingleR.annotation.ref.Blueprint = celldex::BlueprintEncodeData(cell.ont = "nonna")
  
  x.sce = as.SingleCellExperiment(DietSeurat(x.integrated))
  
  # Run automated annotation using several different references
  singleR.main.Monaco = SingleR(test = x.sce, assay.type.test = 1, ref = SingleR.annotation.ref.Monaco,labels = SingleR.annotation.ref.Monaco$label.main)
  singleR.main.DbImmune = SingleR(test = x.sce, assay.type.test = 1, ref = SingleR.annotation.ref.DbImmune,labels = SingleR.annotation.ref.DbImmune$label.main)
  singleR.main.Blueprint = SingleR(test = x.sce, assay.type.test = 1, ref = SingleR.annotation.ref.Blueprint,labels = SingleR.annotation.ref.Blueprint$label.main)
  
  singleR.fine.Monaco = SingleR(test = x.sce, assay.type.test = 1, ref = SingleR.annotation.ref.Monaco,labels = SingleR.annotation.ref.Monaco$label.fine)
  singleR.fine.DbImmune = SingleR(test = x.sce, assay.type.test = 1, ref = SingleR.annotation.ref.DbImmune,labels = SingleR.annotation.ref.DbImmune$label.fine)
  singleR.fine.Blueprint = SingleR(test = x.sce, assay.type.test = 1, ref = SingleR.annotation.ref.Blueprint,labels = SingleR.annotation.ref.Blueprint$label.fine)
  
  x.SingleR = x.integrated
  
  # Testing and plotting Monaco main
  x.SingleR$labels_monaco_main = singleR.main.Monaco$pruned.labels
  Idents(x.SingleR) = "labels_monaco_main"
  DimPlot(x.SingleR, label = T , repel = T)
  ggsave2(paste0(Output.dir,Project_name,"_labelled_", x.celltype, "_cells_SingleR_Monaco_main.pdf"), dpi = 700)
  
  # Testing and plotting DbImmune main
  x.SingleR$labels_Db_main = singleR.main.DbImmune$pruned.labels
  Idents(x.SingleR) = "labels_Db_main"
  DimPlot(x.SingleR, label = T , repel = T)
  ggsave2(paste0(Output.dir,Project_name,"_labelled_", x.celltype, "_cells_SingleR_DbImmune_main.pdf"), dpi = 700)
  
  # Testing and plotting Blueprint main
  x.SingleR$labels_Blueprint_main = singleR.main.Blueprint$pruned.labels
  Idents(x.SingleR) = "labels_Blueprint_main"
  DimPlot(x.SingleR, label = T , repel = T)
  ggsave2(paste0(Output.dir,Project_name,"_labelled_", x.celltype, "_cells_SingleR_Blueprint_main.pdf"), dpi = 700)
  
  # Testing and plotting Monaco fine
  x.SingleR$labels_monaco_fine = singleR.fine.Monaco$pruned.labels
  Idents(x.SingleR) = "labels_monaco_fine"
  DimPlot(x.SingleR, label = T)
  DimPlot(x.SingleR, label = T , repel = T)
  ggsave2(paste0(Output.dir,Project_name,"_labelled_", x.celltype, "_cells_SingleR_Monaco_fine.pdf"), dpi = 700,
          width = 20, height = 20)
  
  # Testing and plotting DbImmune fine
  x.SingleR$immune_labels_DbImmune_fine = singleR.fine.DbImmune$pruned.labels
  Idents(x.SingleR) = "immune_labels_DbImmune_fine"
  DimPlot(x.SingleR, label = T , repel = T)
  ggsave2(paste0(Output.dir,Project_name,"_labelled_", x.celltype, "_cells_SingleR_DbImmune_fine.pdf"), dpi = 700)
  
  # Testing and plotting Blueprint fine
  x.SingleR$immune_labels_Blueprint_fine = singleR.fine.Blueprint$pruned.labels
  Idents(x.SingleR) = "immune_labels_Blueprint_fine"
  DimPlot(x.SingleR, label = T , repel = T)
  ggsave2(paste0(Output.dir,Project_name,"_labelled_", x.celltype, "_cells_SingleR_Blueprint_fine.pdf"), dpi = 700)
  
}

if (annotation.done == TRUE) {
  # Labelling all as selected celltype
  print(paste0("Plotting",x.celltype ,"labels"))
  x.integrated$x_labelled = x.integrated$seurat_clusters
  x.integrated = SetIdent(x.integrated, value = "Endothelial_labelled")
  x.integrated = RenameIdents(x.integrated, "0" = "X",
                                 "1" = "Y",
                                 "2" = "Z",
                                 "3" = "",
                                 "4" = "",
                                 "5" = "",
                                 "6" = "",
                                 "7" = "",
                                 "8" = "",
                                 "9" = "")
  x.integrated[["x_labelled"]] = Idents(object = x.integrated)
  DimPlot(x.integrated, reduction = "umap", group.by = "x_labelled",
          label = TRUE, repel = TRUE)
  ggsave2(paste0(Output.dir, Project_name, "_UMAP_", x.celltype, "_labelled.pdf"), dpi = 700)
  
  # Ordering the object and adding colours
  Idents(x.integrated) = "x_labelled"
  new.order.labels = c("X", "Y", "Z")
  Idents(x.integrated) <- factor(Idents(x.integrated), levels= new.order.labels)
  x.integrated$Endothelial_labelled <- factor(x.integrated$Endothelial_labelled, levels= new.order.labels)
  
  # 3 colors
  Dimplot.colors = c("#8491B4CC", "#B09C8599", "#F39B7F99", "#00A08799", "#7E6148CC")
  
  # Dimplot of stroma, no groups
  Idents(x.integrated) = "x_labelled"
  DimPlot(x.integrated, cols = Dimplot.colors, raster = FALSE)
  ggsave2(paste0(Output.dir, Project_name, "_no-labels_UMAP_", x.celltype, "_figure_ptdefault.pdf"), dpi = 700)
  
  DimPlot(x.integrated, cols = Dimplot.colors, raster = FALSE, pt.size = 0.5)
  ggsave2(paste0(Output.dir, Project_name, "_no-labels_UMAP_", x.celltype, "_figure_pt0.5.pdf"), dpi = 700)
  
  # Replotting the dotplots, one group
  DotPlot(object = x.integrated, features = Cellmarkers, group.by = "x_labelled",
          cols = c("dodgerblue", "firebrick"), dot.min = 0.1, assay = "RNA", dot.scale = 10) +
    theme(axis.text.x=element_text(angle=90, vjust = 0.3, hjust = 1))
  ggsave2(paste0(Output.dir, Project_name, "_Dotplot_", x.celltype, "_Curated.pdf"), dpi = 700, width = 12)
  
  DotPlot(object = x.integrated, features = Cellmarkers, group.by = "x_labelled",
          cols = c("navajowhite", "firebrick"), dot.min = 0, dot.scale = 10) +
    theme(axis.text.x=element_text(angle=90))
  ggsave2(paste0(Output.dir, Project_name,"_", Norm.assay, "_", x.celltype, "_Marker_Dotplot.pdf"),
          dpi = 700, width = 14)
  
  DimPlot(x.integrated, reduction = "umap", split.by = "Group_Stage")
  ggsave2(paste0(Output.dir, Project_name, "_UMAP_", x.celltype, "_groups_labelled_Split-Group.pdf"), dpi = 700,
          height = 12, width = 20)
  
  # Save the labelled and re-ordered object
  SaveH5Seurat(x.integrated, paste0(Output.dir,Project_name, "_reclustered_labelled.h5seurat"), overwrite = TRUE)
  
  ##Idents(endo.copy) <- factor(Idents(endo.copy), levels= new.order.labels)
  ###endo.copy$Immune_labelled <- factor(endo.copy$Immune_labelled, levels= new.order.labels)
  ###Dimplot.color = RColorBrewer::brewer.pal(16, "Set1")
  DimPlot(x.integrated, cols = Dimplot.colors, raster = FALSE)
  ggsave2(paste0(Output.dir, Project_name, "_no-labels_UMAP_", x.celltype, "_grouped_figure_ptdefault.pdf"), dpi = 700)
  
  DimPlot(x.integrated, cols = Dimplot.colors, raster = FALSE, pt.size = 0.5)
  ggsave2(paste0(Output.dir, Project_name, "_no-labels_UMAP_", x.celltype, "_grouped_figure_pt0.5.pdf"), dpi = 700)
  
  DimPlot(x.integrated, cols = Dimplot.colors, label = TRUE, repel = TRUE)
  ggsave2(paste0(Output.dir, Project_name, "_labels_UMAP_", x.celltype, "_grouped_figure.pdf"), dpi = 700)
  
  x.average = AverageExpression(x.integrated, return.seurat = TRUE)
  
  DoHeatmap(endo.average, features = Cellmarkers, raster = FALSE,
            group.bar = TRUE, group.colors = c(rep("white", length(levels(endo.average)))),
            draw.lines = FALSE, angle = 45, hjust = 0) + 
    scale_fill_gradient2(low = "#2570B7", mid = "seashell", midpoint = 0, high = "#DC0000FF") +
    theme(axis.text.y = element_text(face = "italic"))
  
  ggsave2(paste0(Output.dir, Project_name,"_", Norm.assay, "_", x.celltype, "_groups_Marker_Heatmap.pdf"),
          dpi = 700, height = 14, width = 8)
  
  Idents(x.average) <- factor(Idents(x.average), levels = rev(new.order.labels))
  DoHeatmap(endo.average, features = Endothelial_markers, raster = FALSE, 
            group.bar = TRUE, group.colors = c(rep("white", length(levels(endo.average)))),
            draw.lines = FALSE, angle = 270, hjust = 1) + 
    scale_fill_gradient2(low = "#2570B7", mid = "seashell", midpoint = 0, high = "#DC0000FF") + 
    theme(axis.text.y = element_text(face = "italic", angle = 315))
  
  ggsave2(paste0(Output.dir, Project_name,"_", Norm.assay, "_", x.celltype, "_groups_Marker_Heatmap_flipped.pdf"), 
          dpi = 700, height = 14, width = 8)
  
  # Plotting the integrated object
  print("Plotting of UMAP")
  UMAP_Ident = DimPlot(x.integrated, reduction = "umap", group.by = "orig.ident", label = TRUE, repel = TRUE)
  ggsave2(plot = UMAP_Ident, filename = paste0(Output.dir,Project_name,"_labelled_UMAP_Ident.pdf"), dpi = 700)
  UMAP_Phase = DimPlot(x.integrated, reduction = "umap", group.by = "Phase")
  ggsave2(plot = UMAP_Phase, filename = paste0(Output.dir,Project_name,"_UMAP_Phase.pdf"), dpi = 700)
  UMAP_Label = DimPlot(x.integrated, reduction = "umap", group.by = "seurat_clusters", label = TRUE, repel = TRUE)
  ggsave2(plot = UMAP_Label, filename = paste0(Output.dir,Project_name,"_labelled_UMAP_Clusters.pdf"), dpi = 700)
  UMAP_Group = DimPlot(x.integrated, reduction = "umap", group.by = "Group_Stage",)
  ggsave2(plot = UMAP_Group, filename = paste0(Output.dir,Project_name,"_UMAP_Group_Stage.pdf"), dpi = 700)
  UMAP_original_label = DimPlot(x.integrated, reduction = "umap", group.by = "Labelled_Clusters_SCT.1",)
  ggsave2(plot =  UMAP_original_label, filename = paste0(Output.dir,Project_name,"_Labelled_Clusters_SCT.1.pdf"), dpi = 700)
  print("Done with basic UMAP")  
  
  # QC plotting of newly labbeled clusters      
  Plot_CQ_Endothelial = Plotting_QC(x = x.integrated, group = "x_labelled")
  
}

Plot_CQ_Group.Stage = Plotting_QC(x = x.integrated, group = "Group_Stage")
Plot_CQ_Group.Stage = Plotting_QC(x = x.integrated, group = "Group_Treatment")
Plot_CQ_Pat_nr = Plotting_QC(x = x.integrated, group = "orig.ident")
Plot_CQ_seurat_clusters = Plotting_QC(x = x.integrated, group = "seurat_clusters")

# Generating feature plots
FeaturePlot(x.integrated, features = "percent.mt")
ggsave2(paste0(Output.dir,Project_name, "_FeaturePlot_mtDNA.pdf"), dpi = 700)

FeaturePlot(x.integrated, features = "nCount_RNA")
ggsave2(paste0(Output.dir,Project_name, "_FeaturePlot_nCount_RNA.pdf"), dpi = 700)

FeaturePlot(x.integrated, features = "nFeature_RNA")
ggsave2(paste0(Output.dir,Project_name, "_FeaturePlot_nFeature_RNA.pdf"), dpi = 700)

FeaturePlot(x.integrated, features = "S.Score")
ggsave2(paste0(Output.dir,Project_name, "_FeaturePlot_S-Score.pdf"), dpi = 700)

FeaturePlot(x.integrated, features = "G2M.Score")
ggsave2(paste0(Output.dir,Project_name, "_FeaturePlot_G2M-Score.pdf"), dpi = 700)

if (FindMarker.flag == TRUE) {
  
  # Setting cluster to be tested to SCT clustered
  Idents(object = x.integrated) <- "seurat_clusters"
  DefaultAssay(x.integrated) = "RNA"
  Norm.assay = "RNA"
  
  print("Finding markers")
  endo.markers <-FindAllMarkers(x.integrated, assay = "RNA")
  print("Saving markers as .csv")
  write.csv(endo.markers, paste0(Output.dir, Project_name, "_", Norm.assay, "_seurat_clusters_FindAllMarkers.csv"), quote = F)
  print("Saving markers as .rds")
  saveRDS(endo.markers, paste0(Output.dir, Project_name, "_", Norm.assay, "_seurat_clusters_markers.rds"))
  print("Extracting top 10 markers per cluster")
  top10 = endo.markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_log2FC)
  
  
  print("Generating heatmap")
  endo.heatmap = DoHeatmap(x.integrated, features = top10$gene) + NoLegend()
  ggsave2(filename = paste0(Output.dir, Project_name, "_", Norm.assay, "_seurat_clusters_Top10_Genes_Heatmap.pdf"),
          plot = endo.heatmap,
          dpi = 700)
  
  # Setting cluster to be tested to SCT clustered
  Idents(object = x.integrated) <- "x_labelled"
  DefaultAssay(x.integrated) = "RNA"
  Norm.assay = "RNA"
  
  print("Finding markers")
  endo.markers <-FindAllMarkers(x.integrated, assay = "RNA")
  print("Saving markers as .csv")
  write.csv(endo.markers, paste0(Output.dir, Project_name, "_", Norm.assay, "_FindAllMarkers.csv"), quote = F)
  print("Saving markers as .rds")
  saveRDS(endo.markers, paste0(Output.dir, Project_name, "_", Norm.assay, "_Endo_markers.rds"))
  print("Extracting top 10 markers per cluster")
  top10 = endo.markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_log2FC)
  
  
  print("Generating heatmap")
  endo.heatmap = DoHeatmap(x.integrated, features = top10$gene) + NoLegend()
  ggsave2(filename = paste0(Output.dir, Project_name, "_", Norm.assay, "_Top10_Genes_Heatmap.pdf"),
          plot = endo.heatmap,
          dpi = 700)
  
  
}
